Update Skyblock Member and Skyblock Profile
Hypixel-API-Reborn/hypixel-api-reborn pull request #429
Opened 2023-09-05 14:52 UTC by Johannes7k75

**Please describe changes**

- The last active skyblock profile has now an selected attribute.
- Skyblock members have a few more values
  - experience
  - hotm
  - trophyFish
  - highestMagicalPower
  - Slayers: enderman, blaze and vampire
  - bestiary Level

- [x] I've added new features. (methods or parameters)
- [x] I've added jsdoc and typings.
- [ ] I've fixed bug. (*optional* you can mention a issue if there is one)
- [ ] I've corrected the spelling in README, documentation, etc.
- [x] I've tested my code. (`npm run test`)

2023-09-11 09:27 UTC, Johannes7k75 commented
@Kathund if created a new pull request, because i have added more things.

2023-09-11 10:04 UTC, Kathund commented
> @Kathund if created a new pull request, because i have added more things.

Give me like a week i will check this pr

2023-09-12 04:12 UTC, Kathund requested changes

2023-09-12 04:12 UTC, Kathund commented on .prettierrc
Please add a print width of 210 to keep with the eslint rules

2023-09-12 05:59 UTC, Johannes7k75 commented on .prettierrc
Is this file even necessary?
This file doesn't even exists on the main repo.

2023-09-12 12:04 UTC, Kathund commented on .prettierrc
depends if u want to keep the file.
Prettier is very useful in large projects like this. Im bringing it in #429 so you can keep it if you want but the choice will come down to you

2023-09-12 20:54 UTC, Johannes7k75 commented on .prettierrc
You mean #428 or? Print Width is fixed

2023-09-13 02:38 UTC, Kathund commented on .prettierrc
I would never mess up the pr link shhhhh

2023-09-13 11:02 UTC, Kathund requested changes

2023-09-13 11:02 UTC, Kathund commented on src/structures/SkyBlock/SkyblockMember.js
> +    this.hotm = data.m.mining_core?.experience ?? 0;
Can you please explain what the number means? im testing on the user lighthth and it returns 300k+ and im unsure what it means? its not there hotm total xp coz i check so im unsure

2023-09-13 11:02 UTC, Kathund commented on src/structures/SkyBlock/SkyblockMember.js
At line [209](https://github.com/Kathund/hypixel-api-reborn/blob/8f85d8a743c9130699a1ba16ffdc23d1457a7c29/src/structures/SkyBlock/SkyblockMember.js#L209) Is it possible to make it return the stats for kills/deaths like this?

```
{
  kills: {
    total: number,
    mobName: number,
    mobName: number,
    mobName: number,
    mobName: number,
    },
  deaths: {
    total: number,
    mobName: number,
    mobName: number,
    mobName: number,
    mobName: number,
    },
   allOtherStatsEct: :shrug:
 }
 ```

2023-09-13 16:03 UTC, Johannes7k75 commented on src/structures/SkyBlock/SkyblockMember.js
> +    this.hotm = data.m.mining_core?.experience ?? 0;
Its the user has an experience for hotm. [See](https://wiki.hypixel.net/Heart_Of_The_Mountain#Leveling) Cumulative, for the hotm tier

2023-09-13 16:20 UTC, Johannes7k75 commented on src/structures/SkyBlock/SkyblockMember.js
Sure

2023-09-13 23:24 UTC, Kathund approved these changes

2023-09-13 23:26 UTC, Kathund requested changes

2023-09-13 23:26 UTC, Kathund commented on src/structures/SkyBlock/SkyblockMember.js
> +    this.hotm = data.m.mining_core?.experience ?? 0;
If possible can you please make it return in an object like how the skills return?

2023-09-14 21:15 UTC, Johannes7k75 commented on src/structures/SkyBlock/SkyblockMember.js
> +    this.hotm = data.m.mining_core?.experience ?? 0;
Yes it returns now a skill Like object

2023-09-14 21:37 UTC, Johannes7k75 commented on src/structures/SkyBlock/SkyblockMember.js
made it now so that in kills and deaths are only mob names

2023-09-15 06:58 UTC, Kathund approved these changes

2023-09-15 06:59 UTC, Kathund commented
@StavZ Tested on 18de187c988837aac1a80e443528f1f4f3bcc9a2 Everything returns correctly and looks good!

2023-09-15 07:29 UTC, Johannes7k75 commented
@Kathund on the commit is one issue getMemberStats() has as param obg but it should be obj.
So stats should be undefined or so.

2023-09-15 07:31 UTC, Kathund commented
> @Kathund on the commit is one issue getMemberStats() has as param obg but it should be obj.
> So stats should be undefined or so.

should be fine since I see you fixed it and I only tested on that commit

2023-09-20 17:18 UTC, Johannes7k75 commented
any followup?

2023-09-21 02:49 UTC, Kathund commented
> any followup?

There's nothing more that I can do its down to someone who has write access to this repo

2023-09-21 12:15 UTC, merged