New Endpoints
Hypixel-API-Reborn/hypixel-api-reborn pull request #508
Opened 2024-03-13 05:13 UTC by Kathund

## Changes
**Most code is taken from #358 allowing it to be closed**

<ins>**[BREAKING] grouping into .skyblock for sb endpoints**</ins>

Adds new endpoints that are in the api but not supported in reborn

<details>
<summary>Screenshots</summary>

</details>

<details>
<summary>Checkboxes</summary>

- [x] I've added new features. (methods or parameters)
- [x] I've added jsdoc and typings.
- [ ] I've fixed bug. (_optional_ you can mention a issue if there is one)
- [ ] I've corrected the spelling in README, documentation, etc.
- [x] I've tested my code. (`npm run tests`)
- [x] I've check for issues. (`npm run eslint`)
- [x] I've fixed my formatting. (`npm run prettier`)

</details>

2024-03-13 13:19 UTC, ChiefChippy2 requested changes

2024-03-13 13:19 UTC, ChiefChippy2 commented on .gitignore
> +.vscode/settings.json
```suggestion
.vscode/settings.json

```

2024-03-13 13:19 UTC, ChiefChippy2 commented on src/API/skyblock/getAuction.js
> +  const res = await this._makeRequest(`/skyblock/auction?${parameters}`);
imma kms if i wrote this

```suggestion
  let filter = '';
  if (type === 'PROFILE') {
    filter = 'profile';
  } else if (type === 'PLAYER') {
    query = await toUuid(query);
    filter = 'player';
  } else if (type === 'AUCTION') {
    filter = 'uuid';
  } else throw new Error(Errors.BAD_AUCTION_FILTER);
  const res = await this._makeRequest(`/skyblock/auction?${filter}=${query}`);
```

2024-03-13 13:19 UTC, ChiefChippy2 commented on src/Client.js
> +   * @name Client#getSkyblockBingo
```suggestion
   * @name Client.skyblock#getBingo
```
(that's clearly not how you do it is it)

2024-03-13 13:19 UTC, ChiefChippy2 commented on src/structures/SkyBlock/Static/Bingo.js
> +/**
i assume i wrote this

2024-03-14 00:52 UTC, Kathund commented on src/structures/SkyBlock/Static/Bingo.js
> +/**
yes?

2024-03-14 01:12 UTC, Kathund commented
There is no current open mayor election so tests will fail

2024-03-20 02:09 UTC, Kathund commented
@ChiefChippy2

2024-03-22 13:48 UTC, Kathund commented
@ChiefChippy2

2024-03-22 14:52 UTC, ChiefChippy2 commented
will review on weekends

2024-03-24 14:12 UTC, ChiefChippy2 approved these changes

2024-03-24 14:12 UTC, merged